### ISSUE TITLE
Auth broken?

### ISSUE THREAD

**Issue by soaringjupiter** [ornicar/lichess-puzzler#12]
After setting everything up and executing 'yarn run' in /validator/back, the webpage asks to login which Lichess. This fails (for me), ostensibly because due the way the authentication is set up, it does not pass either 'code_challenge_method' or 'code_challenge' parameters to Lichess, resulting in a failed authentication attempt (info taken from https://lichess.org/api#operation/oauth). The resulting oauth-callback has an error description of "error_description=code_challenge_method+required" in the URL. Is there a workaround or am I missing something?

**Comment by ornicar** [comment]
the validator is no longer used, I forgot to delete that part.
