### ISSUE TITLE
Puzzle has two solutions with different first moves. Should be removed from database.

### ISSUE THREAD

**Issue by actor10** [ornicar/lichess-puzzler#13]
Puzzle -> uDMCM

Has two solutions that vary on the first move -> Qc4 & Qe3.
(My understanding is mates can have multiple solutions on the last move only.)

This is in the puzzle database and probably should be removed.

Henry

**Comment by actor10** [comment]
The protected black pawn at e5?

**Comment by niklasf** [comment]
Thanks! Forwarded to an internal list of broken puzzles. Should be exluded from the database soon.
