### ISSUE TITLE
Deep Learning for Validator

### ISSUE THREAD

**Issue by J3698** [ornicar/lichess-puzzler#3]
I'm interested in building a model to estimate the quality (based on user votes) and rating (based on user solves) of puzzles. If it can beat the human baseline, this might save time in validation and help prevent any bad puzzles from making it into the open with high probability. Before attempting this however, I wanted to check if it seems like a useful feature. Thank you!

**Comment by ornicar** [comment]
we're not validating puzzles manually, there are hundreds of thousands of them. The community fill filter them.

We'll soon release the full puzzle database so you can train models with it.
