### ISSUE TITLE
mate_in calculations appear to be incorrect

### ISSUE THREAD

**Issue by mctwynne** [ornicar/lichess-puzzler#4]
Given [this mate in 1 example](https://lichess.org/analysis/fromPosition/5k2/1QR5/8/8/8/8/8/3K4_w_-_-_0_1), [`cook.mate_in`](https://github.com/ornicar/lichess-puzzler/blob/master/tagger/cook.py#L673) calculates `moves_to_mate` to be 0, which results in it incorrectly returning `mateIn5`.

In addition, any mate which is greater than 5, returns `mateIn5`, which is required because of the `TagKind` literal unfortunately.

I'd be happy to put up a PR for this if you'd like.

Cheers.

**Comment by ornicar** [comment]
Thanks but it works perfectly, as you can see for yourself on https://lichess.org/training/themes
